### ISSUE TITLE
Typing "./ cmd" freezes terminal

### ISSUE THREAD

**Issue by nt314p** [mellobacon/Termello#13]
**Describe the bug**
See title.

**To Reproduce**
1. Open Termello
2. Type "./ cmd"
3. Hit enter
4. Terminal freezes

**Expected behavior**
Opens a new command prompt window.

**Desktop (please complete the following information):**
Windows 10, 64 bit.
Using Termello v0.2.0 x64.

**Additional context**
Wish the sick matrix theme would save between openings.

**Comment by nt314p** [comment]
Likely related to #12

**Comment by mellobacon** [comment]
To quote what I put in the changelog: "Attempting to execute a process that requires input (ie powershell, windows cmd, node, etc) does work but does not show in the terminal. This causes it to hang indefinitely." I'm still looking for a fix.

**Comment by mellobacon** [comment]
Oh and I'm working on theme saving too!

**Comment by mellobacon** [comment]
I've finally integrated Powershell so that should fix this problem.
