### ISSUE TITLE
Can't backspace

### ISSUE THREAD

**Issue by mellobacon** [mellobacon/Termello#3]
Need to figure out how to make backspacing work

**Comment by anf** [comment]
Perhaps, for now, we can create an event listener until we find the root of the problem - this *may* help in getting the product out as soon as possible. Or perhaps we can just create a pre-release for those who want to try it out now, that would be neat.

**Comment by mellobacon** [comment]
Thats a good idea. I can make a pre-release for people to try out even though its not fully fixed yet. I just find it annoying you cant backspace every time haha. I will make a pre-release very soon then.

**Comment by mellobacon** [comment]
Bug is fixed. Will be addressed in next release.
