### ISSUE TITLE
Add a terminal based text/code editor [Feature]

### ISSUE THREAD

**Issue by tomlin7** [mellobacon/Termello#5]
**Describe the feature you'd like**
Add a terminal based text/code editor.

additional features request include:

- [x] multi-level undo
- [x] syntax highlighting
- [x] command line history
- [ ] on-line help, spell checking
- [ ] filename completion
- [ ] block operations
- [ ] script language

**Additional context**
The VIM editor - similar
![image](https://user-images.githubusercontent.com/70792552/102303438-29d3a780-3f81-11eb-87c1-f88f48ec799b.png)

**Comment by mellobacon** [comment]
A few things. What do you mean by "multi-level undo", "on-line help", and "block operations"?

**Comment by tomlin7** [comment]
A **multi-level undo** system increases the number of activities that may be reversed. Each important action is recorded internally and the user may invoke the undo function several times to cycle backwards through previous states. Multi-level undo is often paired with a redo command.

the picture below is a good representation of on-line help 
![image](https://user-images.githubusercontent.com/70792552/102316341-c5721180-3f9b-11eb-95a3-2554040e4363.png)

code block is a lexical structure of source code which is grouped together. Blocks consist of one or more declarations and statements. i think you got me.

**Comment by mellobacon** [comment]
Billy! I see you are alive. Were you working on this? (@billyeatcookies)

**Comment by tomlin7** [comment]
yeah I was working on it a while back, but got stuck and then sidetracked :p
